### PR TITLE
feat: Typescript support

### PR DESCRIPTION
**Pull request by SebbeJohansson**
This PR adds proper typescript setup and adds typed moduleoptions.

- [x] module.ts
- [ ] plugin.ts
- [ ] playground.ts

### CODE REVIEW

**Comment by SebbeJohansson** [comment]
@Dawntraoz saw that the `release ci` job failed. The reason for it failing was that I was using the tsconfig.json file from the playground (which many others use, for example [tailwindcss](https://github.com/nuxt-modules/tailwindcss/blob/main/tsconfig.json)).

To allow for building without first building the playground I added the necessary rules manually using a different example as a guide (example being [i18n](https://github.com/nuxt-modules/i18n/blob/next/tsconfig.json#L14-L29)).

It should now build just fine 😄

**Comment by alvarosabu** [comment]
Hi, @SebbeJohansson thanks a lot for this contribution, what if we take advantage of the momentum and we give total Typescript support?

Do you mind if I change the title to "Typescript support"?

**Comment by SebbeJohansson** [comment]
@alvarosabu I think that makes sense! Ill take a look!

**Comment by SebbeJohansson** [comment]
@alvarosabu can you verify if `from "#app"` works in this project at all for you? I cant remember if it ever has.
image

**Comment by alvarosabu** [comment]
Let me check

**Comment by SebbeJohansson** [comment]
I think i made a miss when I did the tsconfig files. I have a change I would like to do:
`lib/tsconfig.json`
```json
{
    "compilerOptions": {
      "target": "ESNext",
      "module": "ESNext",
      "moduleResolution": "Node",
      "strict": false,
      "allowJs": true,
      "resolveJsonModule": true,
      "types": [
        "node"
      ],
      "paths": {
        "#app": [
          "../node_modules/nuxt/dist/app/index"
        ]
      }
    }
  }
  ```
  This is based on a conversation I found here: https://github.com/vuejs/language-tools/issues/586#issuecomment-941575857
  which I had to slightly modify so that it works with the non-conventional setup in this module.
  
  For history purposes:
  `tsconfig.json` in the root extends the file in `lib/tsconfig.json` so the whole workspace uses the same base.
  `lib/tsconfig.json` uses the suggested defaults and adds the `#app` path to all for imports properly.

**Comment by SebbeJohansson** [comment]
@alvarosabu I went a head and added that change so that you can verify it on your end.

**Comment by alvarosabu** [comment]
Merged on feature branch to continue working on it

**Pull request merged**
