### PR TITLE
chore: upgrade packages and fix issue with consola

### PR DESCRIPTION
**Pull request by Dawntraoz**
Upgrade packages and resolve the issue with `consola`.

> Original issue in Nuxt 3.4 as reference -> https://github.com/nuxt/nuxt/issues/20209

### CODE REVIEW

**Comment by alvarosabu** [comment]
@Dawntraoz so the solution is to override the console versions rather than just install it locally?

**Comment by Dawntraoz** [comment]
> @Dawntraoz so the solution is to override the console versions rather than just install it locally?

Exactly @alvarosabu, that's what Daniel recommended https://github.com/nuxt/nuxt/issues/20209#issuecomment-1503803701

**Review by alvarosabu — APPROVED** [review]

**Comment by pi0** [comment]
Hi. Have you tried `npm why consola` in dependency graph? What dependencies require newer version of consola? Normally you shouldn't lock it unless it is an end-project (not a nuxt module)

**Comment by Dawntraoz** [comment]
I will discuss with @pi0 the consola fix, since @nuxt/kit@3.4.1 is the version introducing v3.1.0 from consola. I will check if 3.4.2 fix it

**Pull request closed without merging**
