### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by wesssel**
Hello,

I have added Typscript support for this module for our project. 

If you are interested you can use it.

### CODE REVIEW

**Comment by RobinBertilsson** [comment]
Sweet! Off to a good start!
May I ask where the declaration for `StoryblokBridge` is located @wesssel?

**Comment by wesssel** [comment]
@RobinBertilsson it's from the client SDK, https://github.com/storyblok/storyblok-js-client

The interface is declared global

**Comment by emanuelgsouza** [comment]
@wesssel could you please resolve the conflict on `package.json`?

**Comment by tafelnl** [comment]
Why was this closed? Did the issue move somewhere else? Or?

**Comment by Dav3rs** [comment]
@emanuelgsouza any progress improving typescript support?

**Comment by Dawntraoz** [comment]
Hi @Dav3rs, our new DevRel @alvarosabu is working with Sebbe from the community to make it happen on this PR: https://github.com/storyblok/storyblok-nuxt/pull/296. Check out what they're doing, and maybe add your own comments to make it better 💜

**Pull request closed without merging**
